---
name: Build firmware
on:
  push:
    branches:
    - 'master'
    tags:
      - v*
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency: 
  group: 'fw-build'
  cancel-in-progress: true

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - nv14;el18
          - t12
          - t16
          - t18
          - t8;zorro;commando8
          - tlite;tpro;lr3pro
          - tx12;tx12mk2;boxer
          - tx16s
          - x10;x10-access
          - x12s
          - x7;x7-access
          - x9d;x9dp;x9dp2019
          - x9e;x9e-hall
          - x9lite;x9lites
          - xlite;xlites
    container:
      image: ghcr.io/edgetx/edgetx-dev:latest
      volumes:
        - ${{ github.workspace }}:/src
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build firmware ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
          EDGETX_VERSION_SUFFIX: lang-custom
        run: ./build-firmwares.sh

      - name: Build firmware with HELI ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
          EDGETX_VERSION_SUFFIX: lang-custom
        run: ./build-firmwares-heli.sh

      - name: Build firmware with LUAMIXER ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
          EDGETX_VERSION_SUFFIX: lang-custom
        run: ./build-firmwares-luamixer.sh

      - name: Build firmware with BLUETOOTH ${{ matrix.target }}
        env:
          FLAVOR: ${{ matrix.target }}
          EDGETX_VERSION_SUFFIX: lang-custom
        run: ./build-firmwares-bluetooth.sh

      - name: Package firmware ${{ matrix.target }}
        uses: actions/upload-artifact@v3
        with:
          name: edgetx-firmware-custom
          path: |
            *.zip
          retention-days: 15
          if-no-files-found: error

  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: edgetx-firmware-custom
          path: edgetx-firmware-custom

      - name: Deploy release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: 'release'
          prerelease: false
          generate_release_notes: true
          files: |
            edgetx-firmware-custom/*.zip

      - name: Deploy pre-release
        uses: softprops/action-gh-release@v1
        if:  ${{ !startsWith(github.event.ref, 'refs/tags/v') }}
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: 'latest'
          prerelease: true
          generate_release_notes: true
          files: |
            edgetx-firmware-custom/*.zip
